name: Generate Snake

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          github_user_name: Raf-kun
          outputs: dist/snake.svg

      - name: Push to output branch
        uses: ad-m/github-push-action@v0.6.0
        with:
          branch: output
          folder: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
